Flex support
Zondax/ledger-spacemesh pull request #28
Opened 2024-07-29 13:00 UTC by abenso

Added support for Flex device 
Updated submodules

2024-07-29 13:59 UTC, chcmedeiros requested changes
I think we are only missing the build_package_flex: in the main.yml workflow. It's basically a copy from the stax one.

2024-07-30 07:22 UTC, chcmedeiros approved these changes

2024-07-31 13:26 UTC, emmanuelm41 requested changes
Flex needs to be added on CodeQL CI

2024-07-31 15:07 UTC, neithanmo approved these changes

2024-07-31 16:30 UTC, emmanuelm41 approved these changes

2024-07-31 16:46 UTC, merged